spring.application.name=config-cloud-server
server.port=8888
spring.cloud.config.server.git.uri=file:///C:/Users/ikuna/Stuff/Development/Practice/SpringDev/Microservices-Practice-28Mins/git-localconfig-repo